# Docker compose file. I have 2 servies running,
# The database, which is the dynamodb local and the golang server
version: "3.9"
services:
    # Using the dynamodb local script provided by aws
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal
    # Golang server which runs the dockerfile present in the dir
    server:
        depends_on:
            - dynamodb-local
        build: .
        ports:
            - "80:80"
        environment:
            AWS_ACCESS_KEY_ID: 'dummy'
            AWS_SECRET_ACCESS_KEY: 'dummy'
